//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace CarProject_Server.ImageWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ImageWebServiceSoap", Namespace="http://PaperPark.WebService/WebInterface")]
    public partial class ImageWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ImageInterfaceServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestImageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ImageWebService() {
            this.Url = global::CarProject_Server.Properties.Settings.Default.GXTXWBRZ_Service_ImageWebService_ImageWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ImageInterfaceServiceCompletedEventHandler ImageInterfaceServiceCompleted;
        
        /// <remarks/>
        public event TestImageCompletedEventHandler TestImageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PaperPark.WebService/WebInterface/ImageInterfaceService", RequestNamespace="http://PaperPark.WebService/WebInterface", ResponseNamespace="http://PaperPark.WebService/WebInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImageInterfaceService(string param) {
            object[] results = this.Invoke("ImageInterfaceService", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImageInterfaceServiceAsync(string param) {
            this.ImageInterfaceServiceAsync(param, null);
        }
        
        /// <remarks/>
        public void ImageInterfaceServiceAsync(string param, object userState) {
            if ((this.ImageInterfaceServiceOperationCompleted == null)) {
                this.ImageInterfaceServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImageInterfaceServiceOperationCompleted);
            }
            this.InvokeAsync("ImageInterfaceService", new object[] {
                        param}, this.ImageInterfaceServiceOperationCompleted, userState);
        }
        
        private void OnImageInterfaceServiceOperationCompleted(object arg) {
            if ((this.ImageInterfaceServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImageInterfaceServiceCompleted(this, new ImageInterfaceServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PaperPark.WebService/WebInterface/TestImage", RequestNamespace="http://PaperPark.WebService/WebInterface", ResponseNamespace="http://PaperPark.WebService/WebInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TestImage() {
            this.Invoke("TestImage", new object[0]);
        }
        
        /// <remarks/>
        public void TestImageAsync() {
            this.TestImageAsync(null);
        }
        
        /// <remarks/>
        public void TestImageAsync(object userState) {
            if ((this.TestImageOperationCompleted == null)) {
                this.TestImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestImageOperationCompleted);
            }
            this.InvokeAsync("TestImage", new object[0], this.TestImageOperationCompleted, userState);
        }
        
        private void OnTestImageOperationCompleted(object arg) {
            if ((this.TestImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestImageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ImageInterfaceServiceCompletedEventHandler(object sender, ImageInterfaceServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImageInterfaceServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImageInterfaceServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TestImageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591